# Custom data for person detection


# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: datasets/CODEBRIM-8-2/images/train
val: datasets/CODEBRIM-8-2/images/val

# number of classes
nc: 4

# class names
#names: ['CRACK', 'SPALLATION', 'EFFLORESCENCE', 'EXPOSED_BARS', 'CORROSION_STAIN']
names: ['crack', 'rebar', 'spall', 'peel']